### PR TITLE
Virtual class room app

### PR DESCRIPTION
**Pull request by harshithpabbati**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Just got began testing this out, nice start! Aside from the first few comments I left, I also got some error logs in the console at runtime. The text lists them as warning, but they're being logged as errors:

```
Warning: Failed prop type: Invalid prop `IconAfter` supplied to `ForwardRef(_c)`, expected a ReactNode.
    at _c (webpack-internal:///./components/Button/Button.js:43:23)
    at Intro (webpack-internal:///./components/Prejoin/Intro.js:70:19)
    at main
    at Index (webpack-internal:///./pages/index.js:64:21)
    at App (webpack-internal:///./pages/_app.js:27:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:300:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:804:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:957:26)
window.console.error @ next-dev.js?3515:32
printWarning @ react-jsx-dev-runtime.development.js?17e1:117
error @ react-jsx-dev-runtime.development.js?17e1:93
checkPropTypes @ react-jsx-dev-runtime.development.js?17e1:620
validatePropTypes @ react-jsx-dev-runtime.development.js?17e1:1072
jsxWithValidation @ react-jsx-dev-runtime.development.js?17e1:1192
Intro @ Intro.js?8fbf:68
renderWithHooks @ react-dom.development.js?ac89:14985


Warning: Invalid attribute name: `'data-color'`
    at path
    at g
    at svg
    at IconPen
    at button
    at _c (webpack-internal:///./components/Button/Button.js:43:23)
    at div
    at TrayButton (webpack-internal:///./components/Tray/Tray.js:27:23)
    at footer
    at Tray (webpack-internal:///./components/Tray/Tray.js:81:24)
    at BasicTray (webpack-internal:///./components/Tray/BasicTray.js:311:91)
    at div
    at Container (webpack-internal:///./components/Call/Container.js:35:23)
    at div
    at Room (webpack-internal:///./components/Call/Room.js:43:105)
    at div
    at App (webpack-internal:///./components/App/App.js:45:38)
    at AppStateProvider (webpack-internal:///./contexts/AppStateProvider.js:35:23)
    at ChatProvider (webpack-internal:///./contexts/ChatProvider.js:32:23)
    at TranscriptionProvider (webpack-internal:///./contexts/TranscriptionProvider.js:35:23)
    at WaitingRoomProvider (webpack-internal:///./contexts/WaitingRoomProvider.js:26:23)
    at MediaDeviceProvider (webpack-internal:///./contexts/MediaDeviceProvider.js:42:23)
    at ParticipantsProvider (webpack-internal:///./contexts/ParticipantsProvider.js:55:23)
    at RecoilRoot_INTERNAL (webpack-internal:///./node_modules/recoil/es/recoil.js:4309:3)
    at RecoilRoot (webpack-internal:///./node_modules/recoil/es/recoil.js:4475:5)
    at DailyProvider (webpack-internal:///./node_modules/@daily-co/daily-react-hooks/dist/daily-react-hooks.esm.js:111:23)
    at CallProvider (webpack-internal:///./contexts/CallProvider.js:41:23)
    at UIStateProvider (webpack-internal:///./contexts/UIStateProvider.js:40:23)
    at Index (webpack-internal:///./pages/index.js:64:21)
    at App (webpack-internal:///./pages/_app.js:27:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:300:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:804:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:957:26)
```

**Review by ghost — COMMENTED** [review]
Just a few more things I noticed while running it locally. My feedback so far is about things I noticed at runtime, not nitty-gritty of the code itself yet. 

I was thinking with really large demos like this (not now but maybe next time?), it might be nice to do these as incremental PRs. From a review perspective, I would personally probably miss a lot trying to review such a large PR of >150 files (even seeing that quite a few of them are images :)). If we can break these kinds of demos up into incremental steps that might be much more efficient to review.

**Review by ghost — COMMENTED** [review]
Phew, I _think_ I went through everything on this pass. 🤞 

I really like the new flow of creating a room as a teacher on entry and then inviting students. Will be a much nicer experience if directing prospects to the live demo, without having to have them create the room through the dashboard beforehand.

**Review by ghost — APPROVED** [review]
I've tried to keep up with all the cool new stuff coming in as best I can, and I think this is looking really great. I think it might still be good to polish some of the poll behavior (eg right now it seems to be very easy to accidentally close the poll modal and not be able to get back to it), but I realize we're on a tight schedule as well and we can always keep polishing in followup PRs as needed. 🎉

**Review by jessmitch42 — APPROVED** [review]
Nicely done here! Works well. I added some feedback we'll need to incorporate before making this public (namely the README updates and some code style changes) but overall you've done a great job. I think it would also be beneficial for us to discuss coding style a bit because I think some of my feedback is repeated from other demo apps (it seems like devrel has a bit of a different coding style than solutions so it would be good to discuss that before your next demo to avoid having to make a bunch of app-wide changes). One example: we do require demos to be minimally mobile responsiveness. It doesn't need to be perfect but at least "decent enough" to try on a smaller screen. :)

I know this was a lot of work though so again, nice job!

**Pull request merged**
